GlobalPlanner:
# default false
  allow_unknown: false
# defalt: 1.0
  default_tolerance: 0.4
# dijkstra or A*
  use_dijkstra: true
# quadratic
  use_quadratic: true 
# follow the grid or not 
  use_grid_path: false
# outline map
  #outline_map: false
  
# default false
  old_navfn_behavior: false
# 
  visualize_potential: true
# 
  publish_potential: true
# default 253
  lethal_cost: 253
# default 50
  neutral_cost: 66
# default 3.0 0.55
  cost_factor: 0.55
# 0 to 6
#make turning while driving, save turning time
  orientation_mode: 2
# default 1
#no strict limit
  orientation_window_size: 100
